name: DAB Actions Demo
run-name: DAB Workflow test
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  my_script_using_wif:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: https://dbc-356c5b89-4209.cloud.databricks.com
      DATABRICKS_CLIENT_ID: cf777b84-7e7f-41d6-acf8-70f597c38eef

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Who am i
        run: databricks current-user me
      
      - name: validate bundle
        run: databricks bundle validate --target dev

      - name: Deploy bundle
        run: databricks bundle deploy --target dev